Repository Lyearn/mgod, pull requests merged in 2023-12, with the labels that each got.

#5 doc: add documentation for mgod module
  bsondoc/bson_doc_util.go
  bsondoc/build_bson_doc.go
  dateformatter/date_formatter.go
  entity_mongo_model.go
  entity_mongo_model_test.go
  entity_mongo_model_util.go
  entity_mongo_options.go
  errors/errors.go
  schema/entity_model_schema.go
  schema/entity_model_schema_cache.go
  schema/entity_model_schema_options.go
  schema/entity_model_schema_test.go
  schema/entity_model_schema_utils.go
  schema/fieldopt/default_value_opt.go
  schema/fieldopt/field_opt_tags.go
  schema/fieldopt/field_opts.go
  schema/fieldopt/required_opt.go
  schema/fieldopt/xid_opt.go
  schema/metafield/created_at.go
  schema/metafield/doc_version.go
  schema/metafield/meta_field.go
  schema/metafield/meta_field_keys.go
  schema/metafield/updated_at.go
  schema/metafield/validate_and_add_field_util.go
  schema/schemaopt/schema_options.go
  schema/transformer/convert_field_utils.go
  schema/transformer/date_transformer.go
  schema/transformer/id_transformer.go
  schema/transformer/transformer.go
Labels: documentation

#9 feat: add logic to setup default database connection
  README.md
  connection.go
  docs/basic_usage.md
  docs/union_types.md
  entity_mongo_model.go
  entity_mongo_model_test.go
  entity_mongo_model_util.go
  entity_mongo_options.go
Labels: enhancement

#7 feat: docs site
  .github/workflows/build-docs.yml
  .github/workflows/test-docs.yml
  docs/README.md
  docs/about.md
  docs/basic_usage.md
  docs/field_options.md
  docs/field_transformers.md
  docs/installation.md
  docs/meta_fields.md
  docs/schema_options.md
  docs/union_types.md
  website/.gitignore
  website/README.md
  website/babel.config.js
  website/docusaurus.config.ts
  website/package.json
  website/sidebars.ts
  website/src/components/HomepageFeatures/index.tsx
  website/src/css/custom.css
  website/src/pages/index.tsx
  website/static/.nojekyll
  website/static/icon/arrow-ios-up-outline.svg
  website/static/icon/arrow-left-fill.svg
  website/static/icon/arrow-right-fill.svg
  website/static/icon/chevron-up-fill.svg
  website/static/icon/diagonal-arrow-right-up-fill.svg
  website/static/icon/github-fill.svg
  website/static/icon/plug-large.svg
  website/static/icon/setup-large.svg
  website/static/icon/trending-up-large.svg
  website/static/img/favicon.ico
  website/static/img/logo-with-text.svg
  website/static/img/logo.svg
  website/static/img/social-card.jpg
  website/tailwind.config.js
  website/tsconfig.json
  website/yarn.lock
Labels: website

#12 feat: add wrapper function to support MongoDB transactions
  .golangci.yml
  README.md
  connection.go
  connection_cache.go
  docs/README.md
  docs/basic_usage.md
  docs/meta_fields.md
  docs/multi_tenancy.md
  docs/schema_options.md
  docs/transactions.md
  entity_mongo_model.go
  entity_mongo_model_opts.go
  entity_mongo_model_test.go
  schema/schemaopt/schema_options.go
  transaction.go
  transaction_test.go
Labels: enhancement, module

#13 chore: add ci workflow to test and lint
  .github/workflows/test-module.yml
  README.md
  bsondoc/build_bson_doc.go
  docs/installation.md
  errors/errors.go
  schema/entity_model_schema_cache.go
  schema/fieldopt/default_value_opt.go
  transaction.go
Labels: ci

#14 fix: add missing sidebar pages in advanced guide section
  website/sidebars.ts
Labels: website
